version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    expose:
      - "80"
  
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
